
[functions.parse-voice-command]
enabled = true
verify_jwt = true
import_map = "./functions/parse-voice-command/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/parse-voice-command/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/parse-voice-command/*.html" ]
